#!/usr/bin/env python3
import os, sys
from magma import compile, DefineFromTemplatedVerilogFile

if len(sys.argv) != 2:
    print('usage: genesis3 name\n')
    sys.exit(0)

name = sys.argv[1]
print(name)

modules = DefineFromTemplatedVerilogFile(name+'.vp', N=4)
assert len(modules) == 1

module = modules[0]

buildname = os.path.join('build', module.name)
compile(buildname, module)



