#!/usr/bin/env python3
import sys
from magma import compile
from genesis3 import DefineFromTemplatedVerilogFile

if len(sys.argv) != 2:
    print('usage: genesis3 name\n')
    sys.exit(0)

name = sys.argv[1]
filename = name+'.vp'

main = DefineFromTemplatedVerilogFile(name, filename, N=4)

compile(name, main)



